export const rumors = [
  'The loudest player is not always a Citizen.',
  'Silence can be a strategy.',
  'Trust is the strongest weapon in the room.',
  'Traitors often accuse first.',
  'A saved player may not be a Citizen.',
  'A confident story can still be a lie.',
  'Watch who changes their vote too quickly.',
  'The quietest accusation may be the most dangerous.',
  'A perfect alibi is rarely accidental.',
  'The Overseer sees the flow, not the truth.',
  'Two players agreeing too fast should worry you.',
  'A nervous laugh can hide a sharp plan.',
  'Someone is counting who trusts whom.',
  'A Traitor may defend a Citizen to look clean.',
  'The first name spoken can shape the whole room.',
  'Do not mistake panic for guilt.',
  'Do not mistake calm for innocence.',
  'A Guardian cannot save trust once it is broken.',
  'Every vote leaves a shadow.',
  'A wrong accusation can help the right villain.',
  'People remember confidence more than facts.',
  'A player who never commits is still choosing.',
  'Patterns matter more than speeches.',
  'The safest player may be the best mask.',
  'A saved night changes every theory.',
  'The room always has more information than it admits.',
  'A Traitor wants the Council to feel certain.',
  'The truth often arrives after the vote.',
  'Look for who benefits from confusion.',
  'The night rewards patience.',
  'An honest mistake can still end the game.',
  'The best lie sounds useful.'
];

export const randomRumor = () => rumors[Math.floor(Math.random() * rumors.length)];
